pipeline {
  agent any
  environment {
    DOCKER_IMAGE = "wadkaromkar/my-app:${env.BUILD_NUMBER}"
    MLFLOW_TRACKING_URI = "http://localhost:5001"
  }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build & Test') {
      steps {
        sh 'python3 -m pip install -r app/requirements.txt'
        sh 'python3 -m pytest -q || true'
      }
    }
    stage('Docker Build & Push') {
      steps {
        withCredentials([string(credentialsId: 'docker-hub-token', variable: 'DOCKER_TOKEN')]) {
          sh '''
            echo $DOCKER_TOKEN | docker login -u wadkaromkar --password-stdin
            docker build -t $DOCKER_IMAGE .
            docker push $DOCKER_IMAGE
          '''
        }
      }
    }
    stage('Deploy') {
      steps {
        sh 'ansible-playbook ansible/playbook.yml -i ansible/inventory.ini --extra-vars "image=$DOCKER_IMAGE"'
      }
    }
    stage('MLflow Training') {
      steps {
        sh 'python3 app/train_and_log.py --mlflow_uri $MLFLOW_TRACKING_URI'
      }
    }
  }
  post {
    always {
      archiveArtifacts artifacts: 'app/*.log', allowEmptyArchive: true
    }
  }
}
